# Content
content_width: 800
# Copyright
copyright:
  record: false
  hexo: true
  laughing: true
# Disqus
disqus:
  enable: true
  dsq_url: 'https://coding-note.disqus.com/embed.js'
# Google Analytics
google_analytics: UA-98330531-1
# Header
page_background: http://codingnote.com/page_background.png
page_menu_button: dark
post_background: /default_images/post_background.jpg
post_menu_button: light
title_plancehold: 随笔
author:
  head: /codingnote_logo.png # the codingnote
  signature: A place where we share our ideas about codings.
# Icon
favicon: /codingnote_logo_bw.svg
# SEO
keywords: Computer Science, Technology Blog, Web Development, Ubuntu, Codility
## Social icon list: [facebook, twitter, weibo, wechat, github, stackoverflow, linkin, email, segmentfault, flickr, zhihu, disqus, douban, bilibili]
social:
  - name: Github
    icon: github
    link: https://github.com/C0dingNote
  - name: Email
    icon: email
    link: mailto:zhoujinhaixd@gmail.com
# Footer
